
FROM ubuntu:latest
RUN apt-get update && apt-get install -y\
    valgrind \
    build-essential \
    gdb \
    vim \
    git \
    inetutils-ping
RUN apt-get install -y inetutils-traceroute
RUN apt-get install -y iproute2
